config/routes.rb
Rails.application.routes.draw do
  resources :emails, only: [:new, :index, :create, :show]

  resources :templates


  root "emails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :template
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/template.rb
class Template < ApplicationRecord
  has_many :emails, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
    def index
        @emails = Email.all
    end    

    def new
        @email = Email.new
        @templates = Template.all
    end    

    def create
        @email = Email.new(email_params)

        if @email.save
            # Subscriber.all.each do |subscriber|
                NewsletterMailer.with(email: @email, template: @template).newsletter_email.deliver_now

                # Pass in TEMPLATE_NAME so that the mailer can use that variable to render the corresponding template 
            # end    

            redirect_to emails_path, notice: "Email sent"
        else
            render :new , status: :unprocessable_entity    
        end    
    end  
    
    def show
        @email = Email.find(params[:id])
    end    

    private

    def email_params
        params.require(:email).permit(:subject, :body, :template_id)
    end  

end    

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
    def index
        @templates = Template.all
    end
    
    def new
        @template = Template.new

    end    

    def create
        @template = Template.new(template_params)
        
        if @template.save  
            redirect_to templates_path
        else
            render :new , status: :unprocessable_entity    
        end    

    end 

    def edit
        @template = Template.find(params[:id])
    end    

    def update
        @template = Template.find(params[:id])

        if @template.update(template_params)
            redirect_to templates_path
        else
            render :edit
        end
    end    

    def destroy
        @template = Template.find(params[:id])
      
        @template.destroy
      
        redirect_to templates_path
      end

    private
    
    def template_params
        params.require(:template).permit(:id, :name, :header, :footer, :template_name)
    end

end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.js"></script>
  </head>

  <body>

<%# NAVIGATION %>

<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
        <%= link_to 'Emails', emails_path, class: "block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" %>
        </li>
        <li>
          <%= link_to 'Templates', templates_path, class: "block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" %>
        </li>
      </ul>
    </div>
  </div>
</nav>



    <div id="body-content" class= "max-w-4xl flex flex-col">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/templates/edit.html.erb
<h1>Edit</h1>

<%= form_with model: @template do |form| %>
     <div class="mt-6">
        <%= form.label :template_name, "Template type", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.select :template_name, [["Standard", "standard_email"],["Newsletter", "newsletter_email"], ["Product","product_email"]] %>    
    </div>
    
    <div class="mt-6">
        <%= form.label :name, "Template name", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
         <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="mt-6">
        <%= form.label :body, "Template content", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_area :body, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>    
    </div>

    <div>
      <%= form.submit class: "mt-6 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div> 
  <% end %>  
  

app/views/templates/index.html.erb
<h1> Templates <h1>

  <%= link_to "New template", new_template_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>

<%# TABLE %>
<div class ="relative overflow-x-auto ">
  <table class= "mt-6 w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">
          Name
        </th>
        <th scope="col" class="px-6 py-3">
          Template header
        </th>
        <th scope="col" class="px-6 py-3">
          Template footer
        </th>
        <th scope="col" class="px-6 py-3">
          Actions
        </th>
      </tr>
    </thead>

    <tbody>
      <% @templates.each do |template| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= template.name %></th>
          
          <td><%= template.header %></td>
          <td><%= template.footer %></td>

          <td><%= link_to "Edit", edit_template_path(template), class: "mr-6 text-blue-800" %> 
          
          <%= link_to "Destroy", template, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-red-500" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  

app/views/templates/new.html.erb
<h1>New template </h1>
<div class= "">
  <%= form_with model: @template do |form| %>
    <div class="mt-6">
        <%= form.label :name, "Template name", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
         <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="mt-6">
        <%= form.label :header, "Template header", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_area :header, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>    
    </div>

     <div class="mt-6">
        <%= form.label :footer, "Template footer", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_area :footer, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>    
    </div>

    <div>
      <%= form.submit class: "mt-6 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div> 
  <% end %>  
</div> 